import { Request, Response, NextFunction } from "express";
// ... imports lainnya ...

export const calculatePrice = async (req: Request, res: Response, next: NextFunction) => {
    // ... Masukkan logic hitung harga di sini ...
};